version: '3.8'

services:
  pricetelegrambot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pricetelegrambot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    tmpfs:
      - /app/tmp:size=100M,exec,uid=100,gid=101
    # Add resource constraints to prevent container from using all disk space
    deploy:
      resources:
        limits:
          memory: 500M 